#!/bin/bash

OUT="alsa_output.pci-0000_2f_00.4.analog-surround-51"
IDS="/home/tamber/.soundboard"

# Pause music.
clementine --pause

# Hunt down Clementine
MAYBE_CLEMENTINE=($(pactl list short clients | mawk 'tolower($3) ~ "clementine" {print $1}'))

# Hunt for the stream ID.
CLEMENTINE_ID=0
for possible in ${MAYBE_CLEMENTINE[@]}; do
    CLEMENTINE_ID=$(pactl list short sink-inputs | mawk -v check=$possible '$3 == check {print $1}')
done

# Send the music back to the default place.
pactl move-sink-input ${CLEMENTINE_ID} ${OUT}

sleep 3 # Wait a moment for everything to settle

if [ ! -f "${IDS}" ]; then
    exit 1
fi

while read -r module; do
    if [[ "${module}" =~ ^[0-9]+$ ]]; then
	pactl unload-module "${module}" || true
    fi
done < "${IDS}"

rm "${IDS}"
